spring:
  datasource:
    url: jdbc:mysql://mysql:3306/jerrytoy
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    jwt:
      secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
      expiration: 86400000 # 1 day in milliseconds
      token-prefix: Bearer 
      header: Authorization